#!/bin/sh
### BEGIN INIT INFO
# Provides:          bluealsa
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

bluealsa_args="-p a2dp-source -p a2dp-sink -p hfp-ag -p hsp-ag"
aplay_args="-v"

name=bluealsa
bluealsa_pid_file="/var/run/bluealsa.pid"
aplay_pid_file="/var/run/bluealsa-aplay.pid"

. /etc/init.d/functions

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        start-stop-daemon -S -b --oknodo --pidfile $bluealsa_pid_file -m \
                          --startas /usr/bin/bluealsa -- $bluealsa_args
        start-stop-daemon -S -b --oknodo --pidfile $aplay_pid_file -m \
                          --startas /usr/bin/bluealsa-aplay -- $aplay_args
        amixer sset Heaphones "90%"
        if [ $? != 0 ]; then
            echo "Unable to start $name"
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in 1 2 3 4 5 6 7 8 9 10
        # for i in `seq 10`
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not yet stopped; shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
