#!/bin/sh
### BEGIN INIT INFO
# Provides:          bluez-iot-agent
# Required-Start:    $syslog bluetoothd
# Required-Stop:     $syslog bluetoothd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

name=bluez-iot-agent
prog=/usr/bin/$name
pid_file="/var/run/$name.pid"

. /etc/init.d/functions

RC=0
case "$1" in
    start)
        start-stop-daemon -S -b --pidfile $pid_file -m -x $prog
        status=$?
        if [ $status != 0 ]; then
            >&2 printf '%s\n' "Couldn't start $name"
            RC=1
        fi
        ;;

    status)
        if [ -d /proc/$(cat $pid_file) ]; then
            printf '%s\n' "Running"
        else
            printf '%s\n' "Stopped"
        fi
        ;;

    stop)
        start-stop-daemon -K -x $prog
        ;;

    *)
        echo "Usage: $0 {start|stop|status}"
        RC=1
        ;;

esac
