###############################################################################
# NAME:             Containerfile
#
# AUTHOR:           Ethan D. Twardy <ethan.twardy@gmail.com>
#
# DESCRIPTION:      Builds the eSDK container
#
# CREATED:          09/24/2021
#
# LAST EDITED:      09/26/2021
###

FROM docker.io/library/debian:stretch-slim

RUN apt-get update && apt-get upgrade -y \
        && apt-get install -y \
        python3 \
        python3-pip \
        locales \
        diffstat \
        gawk \
        cpio \
        nano \
        openssh-client
RUN sed -i -e '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
        && dpkg-reconfigure --frontend=noninteractive locales \
        && touch /etc/default/locale
COPY tools/cmd-esdk-container.sh /bin/container-cmd

ARG SERVER_IP=192.168.1.60
RUN printf '%s %s\n' "$SERVER_IP" "edtwardy-yocto.local" >> /etc/hosts

RUN useradd -Um -s /bin/bash yocto
USER yocto
WORKDIR /home/yocto
RUN mkdir -p /home/yocto/poky_sdk
VOLUME /home/yocto/poky_sdk

# RUN mkdir -p /home/yocto/.rustup /home/yocto/.cargo
# RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh \
#         && chmod +x ./rustup.sh \
#         && ./rustup.sh -y

ENTRYPOINT ["/bin/bash"]
CMD ["/bin/container-cmd"]

###############################################################################
